const GameConfig = {
  MainScene: {
    GAME_BOARD_WIDTH_CNT: 10,
    GAME_BOARD_HEIGHT_CNT: 20,
    RENDER_TILE_SIZE: 40,
    RENDER_TILE_SPRITE_ORIGIN_SIZE: 64,
    RENDER_TILE_SPRITE_SHEET_KEY: 'block',
    BACKGROUND_TILE_SPRITE_SHEET_KEY: 'back',
    TIMER_INTERVAL_BLOCK_DOWN: 1000,
  },
};

export default GameConfig;
